#!/bin/bash
# This script is one of the many scripts the lazy developer created
# To run the server without typing the whole 'python manage.py runserver'
# Shit
python manage.py runserver 0.0.0.0:8000

