# Generated by Django 2.0.5 on 2018-06-17 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='opening_paragraph',
        ),
    ]
