# Generated by Django 2.0.5 on 2018-05-21 17:04

from django.db import migrations, models
import upload_validator


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(upload_to='', validators=[upload_validator.FileTypeValidator(allowed_extensions=['.doc', '.docx', '.pdf'], allowed_types=['application/msword'])]),
        ),
    ]
