# Generated by Django 2.0.5 on 2019-01-06 12:29

import django.core.validators
from django.db import migrations, models
import staff.models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to=staff.models.news_image_handler),
        ),
        migrations.AlterField(
            model_name='news',
            name='headline',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='news',
            name='headline_image',
            field=models.ImageField(blank=True, null=True, upload_to=staff.models.news_image_handler, validators=[django.core.validators.FileExtensionValidator(['png', 'jpeg', 'jpg', 'JPG'])]),
        ),
        migrations.AlterField(
            model_name='news',
            name='other_image',
            field=models.ImageField(blank=True, null=True, upload_to=staff.models.news_image_handler),
        ),
        migrations.AlterField(
            model_name='organizationofficer',
            name='school_year',
            field=models.PositiveIntegerField(choices=[(2018, 2018), (2019, 2019)], validators=[django.core.validators.MinValueValidator(2018), django.core.validators.MaxValueValidator(2019)]),
        ),
    ]
