# Generated by Django 2.0.5 on 2018-05-23 12:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20180523_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='file',
            field=models.FileField(blank=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx'])]),
        ),
    ]
