# Generated by Django 2.0.5 on 2018-11-28 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_news_opening'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(null=True, upload_to='organization/<django.db.models.fields.CharField>/logo'),
        ),
    ]
