# Generated by Django 2.0.5 on 2018-05-24 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_auto_20180523_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=200)),
                ('headline_image', models.ImageField(upload_to='')),
                ('text', models.CharField(max_length=10000)),
                ('other_image', models.ImageField(upload_to='news_pictures/%Y/%m/%d')),
            ],
        ),
    ]
