# Generated by Django 2.0.5 on 2018-05-24 04:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='news',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='headline_image',
            field=models.ImageField(upload_to='news_pictures/%Y/%m/%d'),
        ),
    ]
