# Generated by Django 2.0.5 on 2018-05-24 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_auto_20180524_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='news',
            name='author_additional_info',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
