# Generated by Django 2.0.5 on 2018-05-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_auto_20180524_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='text',
            new_name='body_text',
        ),
        migrations.RemoveField(
            model_name='news',
            name='published',
        ),
        migrations.AddField(
            model_name='news',
            name='publish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
