# Generated by Django 2.0.5 on 2018-05-24 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0010_auto_20180524_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='publish_date',
            new_name='published_date',
        ),
    ]
