# Generated by Django 2.0.5 on 2018-05-29 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_organization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='auditor_name',
            new_name='auditor',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='g10_representative',
            new_name='g10_rep',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='g11_representative',
            new_name='g11_rep',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='g12_representative',
            new_name='g12_rep',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='g7_representative',
            new_name='g7_rep',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='g8_representative',
            new_name='g8_rep',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='g9_representative',
            new_name='g9_rep',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='pio_name',
            new_name='pio',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='president_name',
            new_name='president',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='secretary_name',
            new_name='secretary',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='treasurer_name',
            new_name='treasurer',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='vice_president_name',
            new_name='vice_president',
        ),
    ]
