# Generated by Django 2.0.5 on 2018-05-29 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0013_auto_20180529_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='aud_picture',
            field=models.ImageField(null=True, upload_to='organization/<django.db.models.fields.charfield>/profiles'),
        ),
        migrations.AddField(
            model_name='organization',
            name='g10_picture',
            field=models.ImageField(null=True, upload_to='organization/<django.db.models.fields.charfield>/profiles'),
        ),
        migrations.AddField(
            model_name='organization',
            name='g11_picture',
            field=models.ImageField(null=True, upload_to='organization/<django.db.models.fields.charfield>/profiles'),
        ),
        migrations.AddField(
            model_name='organization',
            name='g12_picture',
            field=models.ImageField(null=True, upload_to='organization/<django.db.models.fields.charfield>/profiles'),
        ),
        migrations.AddField(
            model_name='organization',
            name='g7_picture',
            field=models.ImageField(null=True, upload_to='organization/<django.db.models.fields.charfield>/profiles'),
        ),
        migrations.AddField(
            model_name='organization',
            name='g8_picture',
            field=models.ImageField(null=True, upload_to='organization/<django.db.models.fields.charfield>/profiles'),
        ),
        migrations.AddField(
            model_name='organization',
            name='g9_picture',
            field=models.ImageField(null=True, upload_to='organization/<django.db.models.fields.charfield>/profiles'),
        ),
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.ImageField(null=True, upload_to='organization/<django.db.models.fields.charfield>/logo'),
        ),
        migrations.AddField(
            model_name='organization',
            name='pio_picture',
            field=models.ImageField(null=True, upload_to='organization/<django.db.models.fields.charfield>/profiles'),
        ),
        migrations.AddField(
            model_name='organization',
            name='pres_picture',
            field=models.ImageField(null=True, upload_to='organization/<django.db.models.fields.charfield>/profiles'),
        ),
        migrations.AddField(
            model_name='organization',
            name='sec_picture',
            field=models.ImageField(null=True, upload_to='organization/<django.db.models.fields.charfield>/profiles'),
        ),
        migrations.AddField(
            model_name='organization',
            name='tres_picture',
            field=models.ImageField(null=True, upload_to='organization/<django.db.models.fields.charfield>/profiles'),
        ),
        migrations.AddField(
            model_name='organization',
            name='vp_picture',
            field=models.ImageField(null=True, upload_to='organization/<django.db.models.fields.charfield>/profiles'),
        ),
    ]
