# Generated by Django 2.0.5 on 2018-05-29 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0014_auto_20180529_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='org_pictures',
            field=models.ImageField(null=True, upload_to='organization/<django.db.models.fields.charfield>/pictures'),
        ),
    ]
