# Generated by Django 2.0.5 on 2018-05-29 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0015_organization_org_pictures'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='adviser_picture',
            field=models.ImageField(null=True, upload_to='organiation/<django.db.models.fields.charfield>/profiles'),
        ),
    ]
