# Generated by Django 2.0.5 on 2018-05-29 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0016_organization_adviser_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='org_pictures',
        ),
    ]
