# Generated by Django 2.0.5 on 2018-05-29 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0018_auto_20180529_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('abstract', models.CharField(max_length=100)),
                ('published_date', models.DateTimeField()),
                ('file', models.FileField(upload_to='research_papers/<django.db.models.fields.charfield>')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchPaperProponents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.ResearchPaper')),
            ],
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
