# Generated by Django 2.0.5 on 2018-05-30 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0019_auto_20180529_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchpaper',
            name='category',
            field=models.CharField(choices=[('Applied', 'Applied Science'), ('Life', 'Life Science')], max_length=50, null=True),
        ),
    ]
