# Generated by Django 2.0.5 on 2018-05-30 02:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0020_researchpaper_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchpaper',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
