# Generated by Django 2.0.5 on 2018-05-30 02:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0021_auto_20180530_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchpaper',
            name='file',
            field=models.FileField(upload_to='research_papers/<django.db.models.fields.charfield>', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
