# Generated by Django 2.0.5 on 2018-05-30 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0022_auto_20180530_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchpaper',
            name='category',
            field=models.CharField(choices=[('Applied', 'Applied Science'), ('Life', 'Life Science')], default=None, max_length=50),
        ),
    ]
