# Generated by Django 2.0.5 on 2018-05-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0023_auto_20180530_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchpaper',
            name='abstract',
            field=models.CharField(max_length=500),
        ),
    ]
