# Generated by Django 2.0.5 on 2018-05-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0024_auto_20180530_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchpaper',
            name='abstract',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='researchpaper',
            name='title',
            field=models.CharField(max_length=10000),
        ),
    ]
