# Generated by Django 2.0.5 on 2018-05-30 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0025_auto_20180530_1822'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResearchPaperProponents',
            new_name='ResearchProponent',
        ),
    ]
