# Generated by Django 2.0.5 on 2018-05-31 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0026_auto_20180530_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchpaper',
            name='category',
            field=models.CharField(blank=True, choices=[('Applied', 'Applied Science'), ('Life', 'Life Science')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='researchproponent',
            name='research',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proponents', to='staff.ResearchPaper'),
        ),
    ]
