# Generated by Django 2.0.5 on 2018-05-31 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0027_auto_20180531_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='category',
            field=models.CharField(blank=True, choices=[('Main', 'Main'), ('Core Subject', 'Core Subject'), ('Social Science', 'Social Science'), ('Music and Arts', 'Music and Arts')], max_length=50, null=True),
        ),
    ]
