# Generated by Django 2.0.5 on 2018-05-31 13:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0030_auto_20180531_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationofficer',
            name='school_year',
            field=models.PositiveIntegerField(choices=[(2017, 2017)], validators=[django.core.validators.MinValueValidator(2018), django.core.validators.MaxValueValidator(2018)]),
        ),
    ]
