# Generated by Django 2.0.5 on 2018-06-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0035_auto_20180603_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='catchy_phrase',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
