# Generated by Django 2.0.5 on 2018-06-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0036_news_catchy_phrase'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='other_image_label',
            field=models.ImageField(blank=True, null=True, upload_to='news_pictures/%y/%m/%d/other_image_label'),
        ),
    ]
