# Generated by Django 2.0.5 on 2018-06-04 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0037_news_other_image_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='catchy_phrase',
            new_name='opening',
        ),
    ]
