# Generated by Django 2.0.5 on 2018-06-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0039_auto_20180604_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='other_image_label',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
