# Generated by Django 2.0.5 on 2018-06-06 00:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0040_auto_20180604_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='announcement_documents', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx'])]),
        ),
    ]
