# Generated by Django 2.0.5 on 2018-06-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0041_auto_20180606_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
