# Generated by Django 2.0.5 on 2018-06-17 04:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0042_auto_20180616_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='body_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='lead_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='opening',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='researchpaper',
            name='abstract',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='researchpaper',
            name='file',
            field=models.FileField(upload_to='research_papers/<django.db.models.fields.textfield>', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='researchpaper',
            name='title',
            field=models.TextField(),
        ),
    ]
