# Generated by Django 2.2.1 on 2019-07-11 11:16

import django.core.validators
from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='headline_image',
            field=models.ImageField(upload_to=news.models.news_image_handler, validators=[django.core.validators.FileExtensionValidator(['png', 'jpeg', 'jpg', 'JPG'])]),
        ),
    ]
