# Generated by Django 2.0.5 on 2019-04-14 15:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionaccount',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
